---
output: pdf_document
---

## Understanding Emotions in Times of Increased Risk and Uncertainty
The Covid-19 pandemic puts considerable emotional strain on people worldwide. In parallel to negative socio-economic [@Nicola2020] and physical [@WHO2022] effects, mental health diseases have increased rapidly during the early stages of the pandemic [e.g., @Daly2020; @Xiong2020]. Especially certain populations' mental health is affected. For Covid-19 patients and medical staff the risk for developing depression, anxiety or insomnia increased considerably compared to non-medical populations [@WU202191]. Hence, understanding the impact of such extreme events and related political regulations, not only on the physical health in a given population, but also on their psychological well-being and emotions is crucial. Moreover, for the governmental measures to be effective, affected citizens need to confide in the responsible stakeholders to comply with the preventive measures [@Fancourt2020; @Rubin2009]. To effectively communicate regulations to citizens and build trust, understanding their emotions is a potential premise to finally mitigate risk [@Ahn2020; @Meadows2019]. 
Significantly, reactions to pandemics are often linked to emotional changes, especially in anger and anxiety [@Huang2020; @Sang-Hwa2021]. Pandemics symbolize a threat to many, and anxiety increases when people do not feel sufficiently prepared to cope with resulting challenges [@frijda1986]. In the months following the onset of the pandemic in Austria in February 2020, various governmental preventive measures such as lockdowns or the mandatory use of face masks were enforced. The success of these regulations is tightly linked to the compliance of the population. Importantly, self-reported anxiety is a meaningful predictor of people’s degree of conformity. For example, @bults2011 presented results linking increased levels of anxiety to compliance with government-advised preventive measures during early stages of the Influenza A virus in the Netherlands. 
Moreover, anger is induced when people are confronted with negative obstacles in their lives [@Berkowitz1993]. Indeed, in a pandemic situation, anger potentially motivates behavior that counteracts governmental measures [@Huang2020] as these might be perceived as the originator of one’s own worsening situation [@frijda1986]. Contrarily to anger, sadness is not experienced directly after the confrontation with negative conditions but rather slowly as negative consequences due to the pandemic, such as loss or governmental regulations, become more apparent [@Oatley2014]. 
Accordingly, emotions constitute a central part in helping public-health stakeholders foster efficient mitigation strategies that increase the population's well-being. Notably, this is even more clearly for situations like the Covid-19 pandemic in which governmental communication plays a crucial role in how the population reacts and adapts to preventive measures [e.g., @Chou2020]. 


## Theory of Emotions
To leverage knowledge concerning the affective state of a population and guarantee its valid assessment a thorough understanding of emotional affect is warranted.
@Scherer2000 suggested a typology for affective states, ranging from emotion, mood, interpersonal stance to attitude and personality traits. Emotions describe a rather strong reaction to an event that mostly only endures a short period of time [@Scherer2000].  
&nbsp;&nbsp; Historically, an important branch in psychological research has tried to determine basic emotions. @Tracy2011 reviewed four prominent theories about basic emotions, three of which claimed that, among others, anger, sadness and fear represent such emotional entities. As described above, these emotions play a detrimental role in analyzing the reactions to health crises such as pandemic situations.  
&nbsp;&nbsp; An important counterpart of the categorical basic emotion theories is a dimensional approach to describing emotions most prominently represented by the circumplex model of affect. It categorizes specific emotions into a two-dimensional space spanned by two bipolar dimension, an emotion's degree of arousal and pleasure [@russell1980]. @Ortony1988 [pp. 29-32] further underlines the importance of valence and ascribes each emotion a degree of positivity or negativity. Both theoretical backgrounds influenced the development of techniques to assess affect on a population level. 


## Surveys and Sentiment Analyses

Knowledge concerning emotions, trust and attitudes concerning public health measures build an important, nevertheless lacking, foundation for communication strategies for responsible stakeholders. @michie2020 motivated a behavioral science research agenda to fill this knowledge gap that should help to reduce the negative consequences of crises. 
@lang2021 followed these recommendations, and conducted an online survey investigating the attitudes towards governmental preventive measures and Covid-19 vaccines.
Indeed, surveys are a commonly accessed method to capture emotional climates and attitudes within a society in public health and psychological research [see e.g., @fischhoff2018; @NIEDERKROTENTHALER202249].
Even though providing stakeholders with valuable insights, one issue of this method is its feasibility. Surveys are often time-consuming for participants and researchers and economically costly. Moreover, surveys suffer from a diverse range of biases that limit the quality of further analyses [@SACKETT197951]. A prominent example of bias in retrospective study designs is the recall bias that describes the decrease of accuracy in the retrieval of past events. Therefore, other methods that can keep track of emotional change in society would be an asset to complement or substitute surveys and potentially reduce bias.

In recent years the domain of computational social science has been offering the opportunity to gather and handle social media data as a live readout of peoples emotional states [@Lazer2009]. In particular, the field of language processing widened drastically and enables the assessment of different types of affect [see @Scherer2000] depending on the goal of the analysis. In psychological research, emotions are the usual focus of interest. In line with this, extracting emotions from online data employs the ideas developed by the two families of theories of emotions presented above, a categorical approach to basic emotions [@Tracy2011] and a dimensional approach including emotional valence [@russell1980].
Techniques in language processing provide the means to capture emotional valence via sentiment analyses or identify emotions via emotion detection [@Nandwani2021]. More specifically, both valence or polarity association lexica and affect association lexica are in use [@MOHAMMAD2021323]. They successfully match text, for instance social media postings, to expert-created dictionaries containing words that are associated with a given emotion or emotional valence.  Mental health is one domain that could potentially gain further insights on the macroscopic transitions in emotions and well-being via large-scale longitudinal social media data. 
These tools enable researchers to investigate changes in mood on a population level by analyzing the interplay between temporal changes in language and psychological outcomes [@Correia2020]. @Goncalves2015 compared the performance of several computational techniques for language processing in text that can broadly be categorized into dictionary-based and machine learning-based tools. 
On the one hand, dictionary-based tools like the Linguistic Inquiry and Word Count [LIWC, @pennebaker2015] associate text with various emotions. These tools are built on a dictionary of words related to certain emotional states like anger, anxiety and sadness that are then matched with a given text. 
LIWC is a prominent example of such an approach that was already adapted for its use in German text [@Wolf_2008]. Amongst others, LIWC aims at assessing certain emotions like anger, anxiety, sadness, but also constructs like prosociality or positive emotions. To provide a few examples, *Aggression* (aggression) or *hassen* (hate) are part of the anger-related dictionary, words like *aufgeregt* (excited) or *ängstlich* (anxious) correspond to the anxiety library and *depressiv* (depressive) or *einsam* (lonely) are incorporated in the sadness library. @ashokkumar_pennebaker_2021 conducted research employing the English version of LIWC [@pennebaker2015] by examining the transformation of the emotional climate in the US after the outbreak of the Covid-19 pandemic. Whilst sadness and anxiety increased right after the first death related to Covid-19 in the US, both positive emotions and, surprisingly, anger decreased, thereby providing a picture of the emotional states during the onset of a pandemic leveraging live, longitudinal, and introspective data.
On the other hand, machine learning-based text processing algorithms can provide an alternative way of assessing sentiment. The GermanSentiment (GS) tool is a transfer and deep learning-based model specifically tuned for German text [@guhr-etal-2020]. Compared to LIWC, automated text processing methods like GS have a higher coverage of terms that are associated with the respective sentiment [@MOHAMMAD2021323]. Generally, different methods to perform sentiment analyses work on different levels of text. Many dictionary-based methods focus on single words, thus neglecting sentence structure. On the contrary, GS was trained to find low-dimensional continuous representations of sentences and can therefore assess context-dependent word representations within text documents. When provided with a specific set of training data, for instance solely consisting of movie reviews, it singles out the meaning of words in this context. This quality differentiates many machine learning-based from dictionary-based sentiment techniques [@MOHAMMAD2021323].
Importantly, GS does not assess specific emotions but rather emotional valence. GS outputs probabilities mirroring the model's degree of certainty that a given text is either negative, positive, or neutral [@guhr-etal-2020]. Thus, it maps text onto an emotional valence dimension.
Hence, existing tools offer the possibility to investigate psychological states using social media data and effectively analyze the impact of certain events on emotional climates. Sentiment analyses have found their place in domains as diverse as marketing, economy, politics, and health. Indeed, the latter field tends to lack behind the others since domain-specific data is usually not made publicly available [@zunic2020sentiment]. Nonetheless, past research successfully examined health-related emotional transitions on a macroscopic level.  Prominent examples are the analyses of the reaction of societies to traumatic events such as natural disasters or terrorist attacks. Twitter data has been shown to be able to capture the emotional transitions, specifically in negative emotions but also in solidarity after events that impacted local or global societies as a whole, for example after the Paris terrorist attacks in 2015 [@garcia2019collective]. Furthermore, during the Covid-19 pandemic, @Saha2020 investigated the development of psychosocial characteristics using Twitter postings. More specifically, mental health outcomes such as anxiety, depression, stress, suicidal ideation as well as emotional and informational support increased from March to May 2020 in the United States, hence providing an overview of the pandemic's psychological effects.
Another study conducted by @Metzler2021 provided insights that whilst anxiety and sadness related Tweets increased in the initial phases of the Covid-19 pandemic consistently across 18 different countries and six languages, anger related tweets decreased compared to pre-Covid times.


## Substituting Surveys by Social Media Data? 
Although research based on social media data should be handled with care and its validity cannot be taken for granted [see e.g., @chancellor2020methods], the potential of creating monitoring or diagnostic tools for mental health outcomes and providing guidance for public health messaging is promising. 
Considering the capability to capture large-scale characteristics on social media this efficiently, the question arises whether traditional approaches like large-scale representative polls can eventually be substituted by text processing of social media data in case fast access to information is warranted. Different domains already tried to provide an answer whether these two methods measure the same constructs. Especially in the fields of economics, recent studies analyzed whether social media data can complement or even substitute surveys. @Pasek_2018 found that certain economic variables measured by surveys, specifically the perceptions of societal economic change, were related to Twitter data. Another study investigated previously reported associations between consumer sentiment and social media data by exploring different ways of analyzing this link [@Frederick_2019]. Whereas the outcome was sensible to various micro-decisions in the data-analyzing process, for example the choice of the smoothing intervals, they generally could not replicate the original results. In the domain of emotion research, a recent study by @pellert2021 compared daily self-reported short-term emotional states on the website of the Austrian newspaper Der Standard to sentiment measures of the same online platform's as well as Twitter postings. Indeed, they observed convincing associations between the affective states of the users as measured by survey and sentiment analysis. 


## The Present Study

This thesis investigates the prospect of current text processing techniques to measure changes in important psychological outcomes and their potential convergence with survey characteristics.
Similar to the research on collective emotional responses during the first months of Covid-19 conducted by @Metzler2021, this study primarily focuses on anger, anxiety and sadness as indicators of change due to the pandemic situation.
This research aims at answering the question whether representative surveys that assess the emotional climate of a society measure the same constructs as dictionary-based or alternatively machine learning-based sentiment analyses. To investigate this, potential commonalities of affect-measures of a repeated cross-sectional Austrian representative survey conducted by @NIEDERKROTENTHALER202249 with aggregates of affective expressions on social media are analyzed. Compared to the research conducted by @pellert2021, this study investigates the association with a survey that is representative for the Austrian population, and not uniquely for the online social media community. Furthermore, whereas the study by @pellert2021 used one concise question as a self-reported measure, various validated scales assessed psychological constructs in this study's survey. Since the same social media platforms as well as the same text processing methods (LIWC and GS) are employed, it is of interest whether this study's results converge with the ones of @pellert2021.

Specifically, the present study examines the adequacy of both Twitter and forum postings of Der Standard - an Austrian newspaper - in complementing or substituting surveys as a polling method for macroscopic affective states. The survey data contained in this study had been conducted every three weeks from April to December 2020, resulting in 12 waves. Like the research by @ashokkumar_pennebaker_2021, the authors surveyed various emotional and health-related characteristics in the Austrian population during a time of repeating lockdowns and following relaxations (see @NIEDERKROTENTHALER202249 for thorough analyses on the survey data set). Firstly, this thesis studies the associations between self-reported anger, anxiety and depression and the sentiment and emotion scores of Austrian Twitter and Der Standard forum users in a confirmatory approach. Second, it investigates the effect of the time window for which we included the social media data on the aforementioned association and the link between further self-reported positive and negative life outcome variables and LIWC and GS scores in an exploratory manner. 


